## Prelims.

```{r prelims, cache=FALSE, message=FALSE, warnings=FALSE, results='hide'}
library(data.table)
library(knitr)
library(lubridate)
library(dplyr)
library(raster)
library(tidyr)

# read the county-level COVID19 case, death and population data, and a county shapefile
data_dir <- "/Users/cyborginhas/Desktop/Datasources/"
county_shp <- shapefile(file.path(data_dir, "cb_2015_us_county_20m", "cb_2015_us_county_20m.shp"))
# data from "USA FACTS" website: https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/
covid_cases <- fread(file.path(data_dir, "covid_confirmed_usafacts.csv"))
covid_countypop <- fread(file.path(data_dir, "covid_county_population_usafacts.csv"))
```

## Preprocessing - confirmed cases daily counts, confirmed cases daily cumulative counts

```{r data_prep, tidy=TRUE, cache=TRUE, message=FALSE, warning=FALSE, results='hide'}
    # join the county population data
    covid_cases <- merge(covid_countypop[, .(countyFIPS, population)], covid_cases,
                         by="countyFIPS")
    # fix the column name
    names(covid_cases)[3] <- "county" # get rid of space in var name
    names(covid_cases)[4] <- "state"
    # change case count variable names to dates
    covid_dates <- as.Date(names(covid_cases)[6:ncol(covid_cases)],
                           format="%m-%d-%y")
    #transpose covid cases to calculate daily totals
    covid_cases_l<-gather(covid_cases,dates,clm_d_confirmed,6:247)
    covid_cases_l$dates<-mdy(covid_cases_l$dates)
    #calculate daily counts per county
    covid_cases_l<-as.data.table(covid_cases_l)
    covid_cases_l<-covid_cases_l[order(county,state,dates),]
    covid_cases_l = covid_cases_l %>% group_by(countyFIPS) %>% 
        mutate(d_confirmed = clm_d_confirmed-lag(clm_d_confirmed))
    covid_cases_l$county<-tolower(covid_cases_l$county)
    covid_cases_l$state<-tolower(covid_cases_l$state)
    write.csv(covid_cases_l,"covid_confirmed_clean.csv")
```