<!-- knit2html("GIS713_DataChallenge_2020.Rmd") -->


## Prelims
Some COVID-19 data from the USA Facts website is available on Moodle. We'll load those data and make some quick figures.

```{r prelims, cache=FALSE, message=FALSE, warnings=FALSE, results='hide'}
library(raster)
library(data.table)
library(viridis)
library(knitr)

# read the county-level COVID19 case, death and population data, and a county shapefile
data_dir <- "/Users/martineelisabethmathieu/Documents/NCSU /FALL 2020/GIS 713/DATA CHALLENGE"
county_shp <- shapefile(file.path(data_dir, "cb_2015_us_county_20m", "cb_2015_us_county_20m.shp"))
# data from "USA FACTS" website: https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/
covid_cases <- fread(file.path(data_dir, "covid_confirmed_usafacts.csv"))
covid_countypop <- fread(file.path(data_dir, "covid_county_population_usafacts.csv"))
covid_deaths <- fread(file.path(data_dir, "covid_deaths_usafacts.csv"))
```

## Preprocessing


```{r data_prep, tidy=TRUE, cache=TRUE, message=FALSE, warning=FALSE, results='hide'}
    # join the county population data
    covid_cases2 <- merge(covid_countypop[, .(countyFIPS, population)], covid_cases, by="countyFIPS")
    
    # fix the names to be R-compliant
    names(covid_cases2)
    names(covid_cases2)[3] <- "countyName" # get rid of space in var name
    # change case count variable names to be dYYYYJJJ format
    covid_dates <- as.Date(names(covid_cases2)[6:ncol(covid_cases2)], format="%m/%d/%y")
    names(covid_cases2)[6:ncol(covid_cases2)] <- strftime(covid_dates, format="d%Y%j")

    # NOTE: there are records for "Statewide Unallocated"
    # maybe they should be distributed evenly? There are nontrivial case numbers:
    covid_cases2[countyName == "Statewide Unallocated", .(countyName, State, d2020259)]

    # let's calculate the per capita cases across all observation dates
    case_cols <- names(covid_cases2)[6:ncol(covid_cases2)]
    new_names <- paste(case_cols, "pc", sep="_")
    covid_cases2[, (new_names) := lapply(.SD, function(cases) cases / population), .SDcols=case_cols]

```




## Election data
```{r}
county_pres <- fread(file.path(data_dir, "countypres_2000-2016.csv"))
county_pres_2016 <- county_pres[year == 2016 & (party == "democrat" |  party == "republican")]

# Replace "democrat" by 1 (Yes) and "republican" by 0 (No)
county_pres_2016[party == "democrat", party := "1"]
county_pres_2016[party == "republican", party := "0"]


 # Change FIPS name to countyFIPS
setnames(county_pres_2016, "FIPS", "countyFIPS")

covid_cases3 <- merge(county_pres_2016[, .(countyFIPS, candidate, party, candidatevotes, totalvotes)], covid_cases2, by="countyFIPS")


# Using the last date variable name
covid_red_blue <- glm(d2020198_pc ~ party, family = binomial (link="logit"), data = covid_cases3)
summary(covid_red_blue)
#plot(covid_red_blue)
# No relationship at all


# Let's check if there is relationship between dem voters and covid19

covid_cases3[, voters_pc := candidatevotes / totalvotes]

covid_cases3_win <- covid_cases3[covid_cases3[, .I[voters_pc == max(voters_pc)], by=countyFIPS]$V1] 

covid_cases3_DemWin <- covid_cases3_win[party == "1" ]



# Map of the county-level, per capita cases
county_shp$countyFIPS <- as.integer(paste(county_shp$STATEFP, county_shp$COUNTYFP, sep="")) # for merging

county_covid_Dem <- merge(county_shp, covid_cases3_DemWin, by="countyFIPS")
    # as.Date("2020241", format="%Y%j") # which date is this?
spplot(county_covid_Dem, "d2020198_pc", xlim=c(-130, -65), ylim=c(25, 50), col=NA, col.regions=plasma(100))

# glm
covid_glm <- glm(d2020198_pc ~ voters_pc,  family = binomial (link="logit"), data = covid_cases3_DemWin)
summary(covid_glm)

#lm
covid_lm <- lm(d2020198_pc ~ voters_pc, data = covid_cases3_DemWin)
summary(covid_lm)
plot(covid_cases3_DemWin$d2020198_pc ~ covid_cases3_DemWin$voters_pc)

# Test for extreme observations
library(car)
outlierTest(covid_lm)                # Bonferonni p-value for most extreem obs

qqPlot( covid_lm, main="QQ Plot" )   # qq plot for studentized residuals
leveragePlots(covid_lm)              # leverage plots

# Remove 2 extreme values rows 125 and 327
covid_cases3_Dem_removed <- covid_cases3_DemWin[-c(125,327)]

# Plot again

# glm
covid_glm2 <- glm(d2020198_pc ~ voters_pc,  family = binomial (link="logit"), data = covid_cases3_Dem_removed)
summary(covid_glm2)

# lm
covid_lm2 <- lm(d2020198_pc ~ voters_pc, data = covid_cases3_Dem_removed)
summary(covid_lm2)
plot(covid_cases3_Dem_removed$d2020198_pc ~ covid_cases3_Dem_removed$voters_pc)


```



